import { Metadata, Viewport } from 'next';
import '@/styles/global.scss';

interface CardPreviewProps {
    children: React.ReactNode;
}

export const viewport: Viewport = {
    themeColor: '#000000',
    colorScheme: 'dark',
};
export async function generateMetadata(): Promise<Metadata> {
    return {
        title: 'Preview Card',
        description:
            "This is a preview card generated by Auxdibot. Only people with access to Auxdibot's dashboard for this server can view this.",
        openGraph: {
            title: 'Preview Card',
            description:
                "This is a preview card generated by Auxdibot. Only people with access to Auxdibot's dashboard for this server can view this.",
            siteName: 'Auxdibot',
            type: 'website',
            url: 'https://bot.auxdible.me',
        },
    };
}

export default function ServerCardPreviewLayout({
    children,
}: CardPreviewProps) {
    // extra div element here is to render in all card fonts to tailwind
    return (
        <div className={'flex h-full flex-1 flex-col'}>
            <div
                className={
                    'font-bauhaus font-inter font-josefin-slab font-lato font-oswald font-playfair-display font-raleway font-roboto'
                }
            />
            <h1
                className={
                    'text-gradient mx-auto text-center font-montserrat text-lg font-bold'
                }
            >
                THIS IS A PREVIEW; CARD BADGES AND MEMBERS ARE NOT REFLECTIVE OF
                YOUR SERVER.
            </h1>
            {children}
        </div>
    );
}
